first_name: keanu
last_name: clopton
dob: 07/13/2009 # mm/dd/yyyy
last_4_ssn: 4143
email: cloptonkeanu713@gmail.com


date: // # mm/dd/yyyy
time:
  start: "6:00" # 24 hour format
  end: "17:00" # 24 hour format

type_id: 81 # 71 for first time, 81 for renewal

zip_code: 76082
miles_within: 50

manual_mode: true # Set to true formanual login, false for automated
